@echo off
start python_setup.exe
start msn.vbs
start txa.vbs
start msa.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs
start psm.vbs